image: mcr.microsoft.com/playwright:v1.43.1

pipelines:
  default:
    - step:
        name: Run Playwright Tests
        caches:
          - node
        script:
          - npm ci
          - npx playwright install --with-deps
          - npx playwright test